import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { apiClient, apiServer } from "../utils/apiClient";
import { TestItem, TestItemResponse } from "../types/TestItem";

interface Props {
  data: TestItem[]
}

export const getServerSideProps: GetServerSideProps = async () => {

  let data: TestItem[] = []

  await apiServer.get<TestItemResponse[]>('testAll')
    .then((res) => {

      data = res.data

    }).catch(err => {
      console.error(`[index][getServerSideProps]`)
      console.error(err)
    })

  return {
    props: {
      data
    }
  }
}

export async function postData(): Promise<TestItem | null> {

  let data: TestItem = {
    id: 0,
    text: '',
    updated_at: '',
    created_at: ''
  }

  return apiClient.post<TestItemResponse>('test', { text: `検証 テスト_${Math.ceil(Math.random() * 100)}` })
    .then(res => {
      const item: TestItemResponse = res.data
      data = { ...item }
      console.log(data)
      return data
    }).catch(e => {
      console.error(e)
      return null
    })
}

const Home: NextPage<Props> = (props) => {

  const router = useRouter()

  const refreshData = () => {
    router.replace(router.asPath);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} style={{ cursor: "pointer" }} onClick={() => {
          postData();
          refreshData();
        }}>
          Welcome to Next.js!
        </h1>
        <ul>{props.data.map((elem: TestItem) => {
          return <>
            <Link href={`/test/${elem.id}`} key={elem.id}>
              <li key={elem.id}>{elem.text}</li>
            </Link>
          </>
        })}</ul>
        {/* <h2>{props.data.text}</h2> */}

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home